on:
  push:
    branches:
      - 'main'

name: Create RPM Release

permissions:
  contents: write
  pull-requests: write
jobs:
    build:
        name: Create RPM Release
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@master

        - name: Run Release Please
          id: release
          uses: google-github-actions/release-please-action@v4
          with:
                token: ${{ secrets.GITHUB_TOKEN }}
                config-file: release-please-config.json
                manifest-file: .release-please-manifest.json

        - name: build RPM package
          id: rpm_build
          if: steps.release.outputs.releases_created
          uses: naveenrajm7/rpmbuild@master
          with:
              spec_file: "espeak-as-say.spec"
            
        - name: Upload Release Asset
          id: upload-release-asset 
          if: steps.release.outputs.releases_created
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.release.upload_url }}
              asset_path: ${{ steps.rpm_build.outputs.rpm_dir_path }}
              asset_name: ${{ steps.rpm_build.outputs.source_rpm_name }}
              asset_content_type: ${{ steps.rpm_build.outputs.rpm_content_type }}
